title: I Do With Liu Docs
description: Instructions and Documentation for how to use Melanie and Andrew's wedding website
theme: just-the-docs
color_scheme: "dark"

url: https://docs.idowithliu.com

aux_links:
  I Do With Liu Website: https://idowithliu.com
  Admin Page: https://idowithliu.com/admin/

nav_external_links:
  - title: I Do With Liu Website
    url: https://idowithliu.com
    hide_icon: false
  - title: Admin Page
    url: https://idowithliu.com/admin/
    hide_icon: false

plugins:
  - jekyll-default-layout